# Source: cluster-api-aws/templates/job-post.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: b9bbbb32-f002-4f09-addc-47a16bab229e-capi-aws-post
  namespace: b9bbbb32-f002-4f09-addc-47a16bab229e
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
spec:
  template:
    metadata:
      name: b9bbbb32-f002-4f09-addc-47a16bab229e-capi-aws
    spec:
      serviceAccountName: b9bbbb32-f002-4f09-addc-47a16bab229e-capi-aws
      containers:
      - name: generate-worker-machines
        image: "ghcr.io/openinfradev/python_kubectl_argo:v1.1.0"
        imagePullPolicy: IfNotPresent
        command:
        - timeout
        - 20m
        - /generate_worker_machines.py
        - b9bbbb32-f002-4f09-addc-47a16bab229e
        - b9bbbb32-f002-4f09-addc-47a16bab229e
        volumeMounts:
        - name: vol
          subPath: mp.raw.yaml
          mountPath: /mp.raw.yaml
        - name: vol
          subPath: md.raw.yaml
          mountPath: /md.raw.yaml
        - name: vol
          subPath: generate_worker_machines.py
          mountPath: /generate_worker_machines.py
      - name: wait-and-initialize
        image: "ghcr.io/openinfradev/python_kubectl_argo:v1.1.0"
        imagePullPolicy: IfNotPresent
        command:
        - timeout
        - 20m
        - /wait_and_k8s_init.sh
        - b9bbbb32-f002-4f09-addc-47a16bab229e
        - taco
        - b9bbbb32-f002-4f09-addc-47a16bab229e
        - "true"
        - "true"

        volumeMounts:
        - name: kubeconfig
          subPath: value
          mountPath: /kube.config
        - name: vol
          subPath: node_label.py
          mountPath: /node_label.py
        - name: vol
          subPath: wait_and_k8s_init.sh
          mountPath: /wait_and_k8s_init.sh
        - name: vol
          subPath: argo-register.sh
          mountPath: /argo-register.sh

      volumes:
      - name: kubeconfig
        secret:
          secretName: b9bbbb32-f002-4f09-addc-47a16bab229e-kubeconfig
      - name: vol
        configMap:
          name: b9bbbb32-f002-4f09-addc-47a16bab229e-capi-aws
          defaultMode: 0555
      restartPolicy: OnFailure
