---
apiVersion: v1
kind: Namespace
metadata:
  name: b9bbbb32-f002-4f09-addc-47a16bab229e
  labels:
    name: b9bbbb32-f002-4f09-addc-47a16bab229e
    # It bring the secret 'dacapod-argocd-config' using kubed
    decapod-argocd-config: enabled

