---
# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: b9bbbb32-f002-4f09-addc-47a16bab229e-capi-aws
  namespace: b9bbbb32-f002-4f09-addc-47a16bab229e
  labels:
    helm.sh/chart: cluster-api-aws-0.5.0
    app.kubernetes.io/name: cluster-api-aws
    app.kubernetes.io/instance: cluster-api-aws
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
